### ISSUE TITLE
Form redirects to blank response json page

### ISSUE THREAD

**Issue by joeyt4n** [jeezusplays/IS212-G6T6#15]
**Describe the bug**
The original issue was that on submission of update role listing, it would show the popup modal and immediately redirect to `/updateRoles`, which returns a **black response json page**.

**To Reproduce**
1. Go to 'http://local:8000/role-listings'
2. Click on 'Edit Listing' button for Financial Analyst (Part Time)
3. Edit a field and click 'Update' button
4. See bug

**Expected behavior**
The expected behavior is for the form action on submit to pop up the success/fail modal, allowing the user to click okay or back.

**Screenshots**
![image](https://github.com/jeezusplays/IS212-G6T6/assets/68149788/549de5ae-b308-43ec-b676-59f98eebfa4f)

**Additional context**
@hx240 has managed to change the redirect to go back to the original `update-roles` page, but this means that the modal would disappear pretty fast upon appearing (Only for success role update)

**Comment by hx240** [comment]
**Additional context for the detailing the flow in which the bug occurs:**
1. User submits a form that sends a form action to `/updateRole`
2. `/updateRole` is a route in `web.php`, which will POST the changes as a store to the database
3. As `/updateRole` is not an existing webpage route with a view, it redirects to either an empty blank page, or json response page reflected from the `UpdateRoleController`


**Possible methods that may resolve it:**
1. Ajax JQuery that freezes the form from executing via `event.preventDefault();` , and does the POST action without needing to go through the process of getting redirected to `/updateRole` route

However, this method will break the existing validation modals and fields created by KK, requiring considerable refactoring/recoding effort to make it work.
